server:
  port: 8066
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Adi#1234
    url: jdbc:mysql://localhost:3306/microservices
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:8069

#  eureka:
 #   instance:
  #    prefer-ip-address: true

   # client:
    #  fetch-registry: true
     # register-with-eureka: true
      #service-url:
       # defaultZone: http://localhost:8761/eureka
